import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { createClient } from '@supabase/supabase-js';
import { assertIsolatedEnvironment } from './guard.mjs';
const E=assertIsolatedEnvironment(),raw=await readFile(new URL('../../.env.local',import.meta.url),'utf8'),v=Object.fromEntries(raw.split(/\r?\n/).filter(x=>x&&x.includes('=')).map(x=>[x.slice(0,x.indexOf('=')),x.slice(x.indexOf('=')+1)]));if(v.VITE_SUPABASE_URL!==E.supabaseUrl.replace(/\/$/,''))throw Error('QA_ABORT local mismatch');
const s=createClient(v.VITE_SUPABASE_URL,v.VITE_SUPABASE_ANON_KEY,{auth:{persistSession:false}}),owner={role:'owner',email:`owner-${E.runId}@example.test`,pass:'Synthetic-owner-A1!'},applicant={role:'applicant',email:`applicant-${E.runId}@example.test`,pass:'Synthetic-applicant-A1!'};
async function ensure(a){let r=await s.auth.signUp({email:a.email,password:a.pass});if(!r.data.user)r=await s.auth.signInWithPassword({email:a.email,password:a.pass});if(r.error)throw r.error;const id=r.data.user.id;await s.auth.signOut();return id}const ownerId=await ensure(owner),applicantId=await ensure(applicant);
async function login(p,a){await p.goto(E.appUrl);await p.locator('input[type=email]').waitFor();await p.getByRole('button',{name:'Sign In',exact:true}).first().click();await p.locator('input[type=email]').fill(a.email);await p.locator('input[type=password]').fill(a.pass);await p.getByRole('button',{name:/^Sign In/i}).last().click();await p.waitForTimeout(700)}
const title=`R6 opportunity ${E.runId}`,msg=`I bring synthetic execution experience and reliable availability for ${E.runId}.`,R={run_id:E.runId,local_only:true,personas:[{...owner,id:ownerId,pass:undefined,personality:'cautious opportunity owner'},{...applicant,id:applicantId,pass:undefined,personality:'persistent evidence-minded applicant'}],checks:{},positive_feedback:[],negative_feedback:[],improvements:[],defects:[],started_at:new Date().toISOString()};const b=await chromium.launch({channel:'chrome',headless:true});
try{const oc=await b.newContext(),op=await oc.newPage();await login(op,owner);await op.goto(`${E.appUrl}#/create-opportunity`);await op.getByPlaceholder(/House-flipping/).fill(title);await op.getByPlaceholder(/Describe the opportunity/).fill('Synthetic R6 application workflow verification.');await op.getByRole('button',{name:/Continue/}).click();await op.getByPlaceholder('City, State').fill('Test City, NY');await op.getByPlaceholder(/Renovate and sell/).fill('Verify owner-controlled applications');await op.getByRole('button',{name:/Continue/}).click();await op.getByPlaceholder(/Role title/).fill('R6 Builder');await op.getByRole('button',{name:/Continue/}).click();await op.getByRole('button',{name:/Continue/}).click();await op.getByRole('button',{name:/^Publish/}).click();await op.waitForTimeout(800);await s.auth.signInWithPassword({email:owner.email,password:owner.pass});const{data:os}=await s.from('opportunities').select('id').eq('owner_id',ownerId).eq('title',title).limit(1);await s.auth.signOut();const oid=os[0].id;R.checks.opportunity_created=!!oid;await oc.close();
const ac=await b.newContext(),ap=await ac.newPage();await login(ap,applicant);await ap.goto(`${E.appUrl}#/opportunity?opportunityId=${oid}`);await ap.getByRole('button',{name:/Apply to collaborate/}).click();const d=ap.getByRole('dialog');await d.locator('select').selectOption({index:1}).catch(()=>{});await d.getByPlaceholder(/Explain the experience/).fill(msg);await d.getByRole('button',{name:/Submit application/}).click();await ap.waitForTimeout(700);R.checks.application_pending=await ap.getByText(/application is pending/i).isVisible().catch(()=>false);await ap.reload();await ap.waitForTimeout(600);R.checks.pending_after_refresh=await ap.getByRole('button',{name:/Application pending/}).isDisabled().catch(()=>false);await s.auth.signInWithPassword({email:applicant.email,password:applicant.pass});const dup=await s.rpc('submit_opportunity_application',{p_opportunity_id:oid,p_message:msg,p_role_id:null});R.checks.duplicate_pending_blocked=Boolean(dup.error);await s.auth.signOut();
await s.auth.signInWithPassword({email:owner.email,password:owner.pass});let{data:notifs}=await s.from('notifications').select('*').eq('user_id',ownerId);R.checks.owner_notification_links_opportunity=notifs.some(n=>n.link===`opportunity:${oid}`);await s.auth.signOut();
const oc2=await b.newContext(),op2=await oc2.newPage();await login(op2,owner);await op2.goto(`${E.appUrl}#/my-opportunities`);await op2.getByRole('button',{name:'Decline',exact:true}).click();R.checks.owner_sees_application=true;await op2.waitForTimeout(700);await s.auth.signInWithPassword({email:owner.email,password:owner.pass});let{data:spaces}=await s.from('collaboration_spaces').select('id').eq('opportunity_id',oid);R.checks.decline_creates_no_space=spaces.length===0;await s.auth.signOut();await oc2.close();
await s.auth.signInWithPassword({email:applicant.email,password:applicant.pass});({data:notifs}=await s.from('notifications').select('*').eq('user_id',applicantId));R.checks.decline_notifies_applicant=notifs.some(n=>/declined|not accepted/i.test(n.text));await s.auth.signOut();await ap.reload();await ap.waitForTimeout(500);await ap.getByRole('button',{name:/Apply to collaborate/}).click();await ap.getByRole('dialog').getByPlaceholder(/Explain the experience/).fill(`${msg} Reapplication.`);await ap.getByRole('dialog').getByRole('button',{name:/Submit application/}).click();await ap.waitForTimeout(500);await ac.close();
const oc3=await b.newContext(),op3=await oc3.newPage();await login(op3,owner);await op3.goto(`${E.appUrl}#/my-opportunities`);await op3.getByRole('button',{name:'Accept',exact:true}).click();await op3.waitForTimeout(900);await s.auth.signInWithPassword({email:owner.email,password:owner.pass});({data:spaces}=await s.from('collaboration_spaces').select('id,space_members(user_id,role)').eq('opportunity_id',oid));await s.auth.signOut();R.checks.accept_creates_exactly_one_space=spaces.length===1;const members=spaces[0]?.space_members||[],sid=spaces[0]?.id;R.checks.roles_correct=members.some(m=>m.user_id===ownerId&&m.role==='Lead')&&members.some(m=>m.user_id===applicantId&&m.role==='Contributor');await oc3.close();
await s.auth.signInWithPassword({email:applicant.email,password:applicant.pass});({data:notifs}=await s.from('notifications').select('*').eq('user_id',applicantId));R.checks.accepted_notification_links_space=notifs.some(n=>n.link===`space:${sid}`&&/accepted/i.test(n.text));await s.auth.signOut();const ac2=await b.newContext(),ap2=await ac2.newPage();await login(ap2,applicant);await ap2.goto(`${E.appUrl}#/space?spaceId=${sid}`);R.checks.applicant_reads_space=await ap2.getByText(title,{exact:true}).first().isVisible().catch(()=>false);await ap2.reload();await ap2.waitForTimeout(700);R.checks.applicant_refresh_reads_space=await ap2.getByText(title,{exact:true}).first().isVisible().catch(()=>false);await ac2.close();
const oc4=await b.newContext(),op4=await oc4.newPage();await login(op4,owner);await op4.goto(`${E.appUrl}#/space?spaceId=${sid}`);R.checks.owner_reads_space=await op4.getByText(title,{exact:true}).first().isVisible().catch(()=>false);await op4.goto(`${E.appUrl}#/profile?profileId=${applicantId}`);await op4.locator('button.text-red-600').click();await op4.getByPlaceholder(/Describe the concern/).fill(`Synthetic report success verification ${E.runId}`);await op4.getByRole('button',{name:/Submit report/}).click();await op4.waitForTimeout(700);R.checks.report_success_status=await op4.getByRole('status').getByText(/Report submitted/i).isVisible().catch(()=>false);await oc4.close();
}catch(e){R.execution_error=e instanceof Error?e.message:String(e)}finally{await b.close()}
for(const [k,vv]of Object.entries(R.checks))(vv?R.positive_feedback:R.negative_feedback).push({persona:k.includes('owner')?'cautious owner':'evidence-minded applicant',check:k,feedback:vv?'The state and consequence were visible and durable.':'The expected state or consequence was not visible.'});for(const[k,vv]of Object.entries(R.checks))if(!vv)R.defects.push({severity:/space|role|decline|accept/.test(k)?'P1':'P2',title:k.replaceAll('_',' ')});if(R.execution_error)R.defects.push({severity:'P1',title:'runner stopped',evidence:R.execution_error});R.improvements.push({priority:'Medium',suggestion:'Show a compact application timeline to both applicant and owner.'},{priority:'Medium',suggestion:'Include the selected role in applicant status and notifications.'});R.passed=!R.execution_error&&R.defects.length===0;R.finished_at=new Date().toISOString();const dir=new URL('./results/',import.meta.url);await mkdir(dir,{recursive:true});const out=new URL(`application-${E.runId}.json`,dir);await writeFile(out,JSON.stringify(R,null,2));console.log(JSON.stringify({report:out.pathname,passed:R.passed,checks:R.checks,defects:R.defects,error:R.execution_error},null,2));if(!R.passed)process.exitCode=1;
