export const scenarios = [
  ['S01', 'Authentication and route recovery', 'Sign up, sign in, refresh, reopen the active route, expire the session, and sign out.'],
  ['S02', 'Profile onboarding and editing', 'Complete and edit every profile field, then verify persistence.'],
  ['S03', 'Authenticated landing actions', 'Verify Finish Profile, View Profile, Explore, and Open Workspace states.'],
  ['S04', 'Opportunity discovery', 'Use all search and filter combinations, clear filters, and inspect empty results.'],
  ['S05', 'Opportunity detail and connection', 'Inspect owner, role, trust, report, apply, and connect actions.'],
  ['S06', 'Opportunity creation', 'Exercise draft, validation, suggestions, preview, publish, refresh, and duplicate submission.'],
  ['S07', 'People and teams search', 'Search people and groups, filter verification, and inspect empty states.'],
  ['S08', 'Profile contact and report', 'Start a conversation and submit a synthetic report with confirmation.'],
  ['S09', 'My Opportunities', 'Verify empty, owned, joined, and restored-route states.'],
  ['S10', 'Collaboration Spaces navigation', 'Test zero, one, many, unauthorized, and missing spaces.'],
  ['S11', 'Task review workflow', 'Create tasks, complete checklists, submit review, approve, discuss, and request changes.'],
  ['S12', 'Workspace modules', 'Exercise milestones, decisions, notes, files, check-ins, records, and module layout.'],
  ['S13', 'Messaging', 'Test direct and space conversations, realtime, unread, failure, retry, and persistence.'],
  ['S14', 'Notifications', 'Open, dismiss, read, mark all read, receive realtime updates, and verify persistence.'],
  ['S15', 'Trust Center', 'Inspect disclaimers and complete report and appeal status flows.'],
  ['S16', 'Professionals marketplace', 'Browse, filter, save, inquire, create a listing, and verify authorization.'],
  ['S17', 'Companies', 'Browse, inspect, create, update, and test company permissions and seats.'],
  ['S18', 'Content and partner surfaces', 'Test Builder Partners, Success Stories, and Resource Center navigation and content.'],
  ['S19', 'Membership and pricing', 'Verify free, trial, paid, past-due, canceling, and expired states.'],
  ['S20', 'Settings', 'Verify identity, privacy, notifications, persistence, errors, retry, and sign out.'],
  ['S21', 'Administration', 'Test guards, users, verification, moderation, reports, audit, collaboration, and subscriptions.'],
  ['S22', 'Resilience and access control', 'Test malformed routes, offline saves, duplicate actions, XSS strings, and cross-user denial.'],
  ['S23', 'Accessibility', 'Complete core flows using keyboard, assistive modes, zoom, focus, and reduced motion.'],
  ['S24', 'Responsive layouts', 'Test primary workflows at mobile, tablet, and desktop viewports.'],
].map(([scenario_id, name, objective]) => ({ scenario_id, name, objective }));
