import type {
  Professional,
  Company,
  BuilderPartner,
  SuccessStory,
  ResourceArticle,
  ID,
} from '@/types';

export const PROFESSIONALS: Professional[] = [
  {
    id: 'pro-1',
    businessName: 'Stone Legal Group',
    logoUrl: 'https://images.pexels.com/photos/5668773/pexels-photo-5668773.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'Attorney',
    description: 'Business law firm specializing in entity formation, contracts, and partnership agreements for growing ventures.',
    services: ['Entity Formation', 'Contract Drafting', 'Partnership Agreements', 'IP Protection'],
    industriesServed: ['Technology', 'Real Estate', 'E-commerce'],
    location: 'Austin, TX',
    remote: true,
    portfolio: [
      { id: 'pf1', title: 'SaaS Partnership Agreement', description: 'Drafted a 3-way equity split for a fintech startup.', imageUrl: 'https://images.pexels.com/photos/5668773/pexels-photo-5668773.jpeg?auto=compress&cs=tinysrgb&w=400' },
    ],
    certifications: ['Texas Bar Association', 'AV Preeminent Rating'],
    website: '',
    yearsInBusiness: 12,
    contactMethods: ['Email', 'Phone', 'Video Call'],
    responseTime: 'Within 4 hours',
    pricingModel: 'Hourly',
    availability: 'Available',
    reviews: [
      { id: 'rev1', authorId: 'p-me', authorName: 'Demo User', rating: 5, text: 'Helped us structure our partnership cleanly. Fair pricing.', at: '2026-05-10', verified: true },
    ],
    verified: true,
    premium: true,
    sponsored: false,
    ownerId: 'p-me',
  },
  {
    id: 'pro-2',
    businessName: 'Ledger CPAs',
    logoUrl: 'https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'CPA',
    description: 'Full-service accounting firm for startups and small businesses. Bookkeeping, tax strategy, and financial planning.',
    services: ['Bookkeeping', 'Tax Strategy', 'Financial Planning', 'Payroll Setup'],
    industriesServed: ['Technology', 'E-commerce', 'Nonprofit'],
    location: 'Remote (Denver, CO)',
    remote: true,
    portfolio: [
      { id: 'pf2', title: 'D2C Brand Tax Optimization', description: 'Saved a $2M ARR brand $40K in unnecessary taxes.', imageUrl: 'https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=400' },
    ],
    certifications: ['CPA Licensed', 'QuickBooks ProAdvisor'],
    website: '',
    yearsInBusiness: 8,
    contactMethods: ['Email', 'Phone'],
    responseTime: 'Within 24 hours',
    pricingModel: 'Retainer',
    availability: 'Available',
    reviews: [
      { id: 'rev2', authorId: 'p-jordan', authorName: 'Jordan Reyes', rating: 5, text: 'Incredible team. Caught deductions we had been missing for years.', at: '2026-04-22', verified: true },
    ],
    verified: true,
    premium: false,
    sponsored: true,
    ownerId: 'p-jordan',
  },
  {
    id: 'pro-3',
    businessName: 'Blueprint Construction',
    logoUrl: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'Contractor',
    description: 'Licensed general contractor for residential and light commercial projects. Renovations, ground-up builds, and tenant improvements.',
    services: ['Renovation', 'Ground-up Construction', 'Tenant Improvement', 'Project Management'],
    industriesServed: ['Real Estate', 'Construction'],
    location: 'Phoenix, AZ',
    remote: false,
    portfolio: [
      { id: 'pf3', title: 'East Austin Bungalow', description: 'Full renovation completed in 4 months.', imageUrl: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=400' },
    ],
    certifications: ['AZ License #ROC-293847', 'OSHA Certified'],
    website: '',
    yearsInBusiness: 15,
    contactMethods: ['Phone', 'Email', 'On-site Visit'],
    responseTime: 'Within 24 hours',
    pricingModel: 'Project-based',
    availability: 'Limited',
    reviews: [
      { id: 'rev3', authorId: 'p-me', authorName: 'Demo User', rating: 4, text: 'Solid work, on time. Communication could be better.', at: '2026-03-15', verified: true },
    ],
    verified: true,
    premium: false,
    sponsored: false,
    ownerId: 'p-jordan',
  },
  {
    id: 'pro-4',
    businessName: 'Northwind Marketing',
    logoUrl: 'https://images.pexels.com/photos/6957188/pexels-photo-6957188.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'Marketing Agency',
    description: 'Growth marketing agency for D2C and B2B brands. Paid ads, lifecycle email, and conversion optimization.',
    services: ['Paid Advertising', 'Email Marketing', 'Conversion Optimization', 'Brand Strategy'],
    industriesServed: ['E-commerce', 'Technology'],
    location: 'Remote (Brooklyn, NY)',
    remote: true,
    portfolio: [
      { id: 'pf4', title: 'Linen Brand Launch', description: 'Scaled a home goods brand from 0 to $1.2M ARR in 14 months.', imageUrl: 'https://images.pexels.com/photos/6957188/pexels-photo-6957188.jpeg?auto=compress&cs=tinysrgb&w=400' },
    ],
    certifications: ['Google Partner', 'Meta Business Partner'],
    website: '',
    yearsInBusiness: 6,
    contactMethods: ['Email', 'Video Call'],
    responseTime: 'Within 4 hours',
    pricingModel: 'Retainer',
    availability: 'Available',
    reviews: [
      { id: 'rev4', authorId: 'p-elena', authorName: 'Elena Rossi', rating: 5, text: 'Best agency I have worked with. They actually understand D2C.', at: '2026-06-01', verified: true },
    ],
    verified: true,
    premium: true,
    sponsored: false,
    ownerId: 'p-elena',
  },
  {
    id: 'pro-5',
    businessName: 'GrantWorks Consulting',
    logoUrl: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'Grant Writer',
    description: 'Grant writing and fundraising strategy for nonprofits and community organizations. 40+ funded grants.',
    services: ['Grant Writing', 'Fundraising Strategy', 'Foundation Research', 'LOI Drafting'],
    industriesServed: ['Nonprofit', 'Community', 'Healthcare'],
    location: 'Seattle, WA',
    remote: true,
    portfolio: [
      { id: 'pf5', title: 'Literacy Initiative Grant', description: 'Secured $480K from a family foundation.', imageUrl: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=400' },
    ],
    certifications: ['Grant Professionals Certified (GPC)'],
    website: '',
    yearsInBusiness: 10,
    contactMethods: ['Email', 'Phone'],
    responseTime: 'Within 24 hours',
    pricingModel: 'Project-based',
    availability: 'Available',
    reviews: [
      { id: 'rev5', authorId: 'p-david', authorName: 'David Kim', rating: 5, text: 'David knows grants inside out. Highly recommend.', at: '2026-02-18', verified: true },
    ],
    verified: true,
    premium: false,
    sponsored: false,
    ownerId: 'p-david',
  },
  {
    id: 'pro-6',
    businessName: 'Apex Financial Advisors',
    logoUrl: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=200',
    category: 'Financial Advisor',
    description: 'Financial planning and investment advisory for business owners and partners. Retirement, tax-advantaged growth, and exit planning.',
    services: ['Financial Planning', 'Investment Advisory', 'Exit Planning', 'Retirement Strategy'],
    industriesServed: ['Technology', 'Real Estate', 'Finance'],
    location: 'Remote (Chicago, IL)',
    remote: true,
    portfolio: [],
    certifications: ['CFP', 'Series 65'],
    website: '',
    yearsInBusiness: 20,
    contactMethods: ['Email', 'Phone', 'Video Call'],
    responseTime: 'Within 24 hours',
    pricingModel: 'Hourly',
    availability: 'Limited',
    reviews: [],
    verified: false,
    premium: false,
    sponsored: false,
    ownerId: 'p-me',
  },
];

export const COMPANIES: Company[] = [
  {
    id: 'co-1',
    name: 'Bright & Co Cleaning',
    logoUrl: 'https://images.pexels.com/photos/4239035/pexels-photo-4239035.jpeg?auto=compress&cs=tinysrgb&w=200',
    description: 'Residential and commercial cleaning company serving the Austin metro area.',
    mission: 'To provide reliable, high-quality cleaning services while creating fair-wage jobs.',
    services: ['Residential Cleaning', 'Commercial Cleaning', 'Post-Construction', 'Recurring Service'],
    industries: ['Cleaning & Services'],
    size: '11-50',
    location: 'Austin, TX',
    website: '',
    contactInfo: '',
    teamMemberIds: ['p-priya', 'p-me'],
    opportunityIds: ['o-clean'],
    portfolio: [
      { id: 'cp1', title: 'Downtown Office Complex', description: 'Weekly cleaning for a 20,000 sqft office building.' },
    ],
    reviews: [
      { id: 'cr1', authorId: 'p-jordan', authorName: 'Jordan Reyes', rating: 5, text: 'Reliable and thorough. Best cleaning company we have used.', at: '2026-05-01' },
    ],
    verified: true,
    ownerId: 'p-priya',
  },
  {
    id: 'co-2',
    name: 'Payloop Technologies',
    logoUrl: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=200',
    description: 'Payments API platform for fintech startups. Acquired in 2023, now building the next iteration.',
    mission: 'To make payments infrastructure accessible to every fintech builder.',
    services: ['Payments API', 'Compliance Tooling', 'Developer SDKs'],
    industries: ['Technology', 'Finance'],
    size: '11-50',
    location: 'Remote (Seattle, WA)',
    website: '',
    contactInfo: '',
    teamMemberIds: ['p-sam'],
    opportunityIds: ['o-tech'],
    portfolio: [
      { id: 'cp2', title: 'Payloop API v2', description: 'Processed $50M in transactions in year one.' },
    ],
    reviews: [
      { id: 'cr2', authorId: 'p-maya', authorName: 'Maya Chen', rating: 5, text: 'Great team, great product. Happy to have been part of it.', at: '2026-04-15' },
    ],
    verified: true,
    ownerId: 'p-sam',
  },
  {
    id: 'co-3',
    name: 'Reyes Holdings LLC',
    logoUrl: 'https://images.pexels.com/photos/3183103/pexels-photo-3183103.jpeg?auto=compress&cs=tinysrgb&w=200',
    description: 'Real estate investment company focused on residential renovations and small multi-family properties.',
    mission: 'To revitalize neighborhoods through thoughtful property renovation and investment.',
    services: ['Property Acquisition', 'Renovation', 'Property Management', 'Investment Partnerships'],
    industries: ['Real Estate'],
    size: '1-10',
    location: 'Phoenix, AZ',
    website: '',
    contactInfo: '',
    teamMemberIds: ['p-jordan'],
    opportunityIds: ['o-flip'],
    portfolio: [
      { id: 'cp3', title: 'Eastside Duplex', description: 'Bought, renovated, sold in 7 months at 22% ROI.' },
    ],
    reviews: [],
    verified: true,
    ownerId: 'p-jordan',
  },
];

export const BUILDER_PARTNERS: BuilderPartner[] = [
  { id: 'bp-1', name: 'Business banking resources', logoUrl: '', category: 'Banking', description: 'Compare account access, fees, controls, and support before choosing a banking provider.' },
  { id: 'bp-2', name: 'Accounting resources', logoUrl: '', category: 'Accounting', description: 'Explore bookkeeping, tax preparation, reporting, and finance-operations support.' },
  { id: 'bp-3', name: 'Business legal resources', logoUrl: '', category: 'Legal', description: 'Find support for formation, contracts, intellectual property, and other business matters.' },
  { id: 'bp-4', name: 'Business insurance resources', logoUrl: '', category: 'Insurance', description: 'Review coverage categories such as general liability, professional liability, and cyber insurance.' },
  { id: 'bp-5', name: 'Payment processing resources', logoUrl: '', category: 'Payments', description: 'Compare tools for accepting, tracking, and reconciling customer payments.' },
  { id: 'bp-6', name: 'Cloud infrastructure resources', logoUrl: '', category: 'Cloud Infrastructure', description: 'Explore hosting, storage, database, and application-infrastructure options.' },
  { id: 'bp-7', name: 'Productivity resources', logoUrl: '', category: 'Productivity', description: 'Compare tools for documents, tasks, planning, and team coordination.' },
  { id: 'bp-8', name: 'CRM resources', logoUrl: '', category: 'CRM', description: 'Explore tools for managing contacts, opportunities, follow-up, and customer relationships.' },
  { id: 'bp-9', name: 'Marketing resources', logoUrl: '', category: 'Marketing', description: 'Review tools for email, campaigns, content, analytics, and audience management.' },
  { id: 'bp-10', name: 'Payroll and HR resources', logoUrl: '', category: 'HR', description: 'Explore payroll, benefits, onboarding, and people-operations tools.' },
];

export const SUCCESS_STORIES: SuccessStory[] = [
  {
    id: 'ss-1',
    title: 'From Opportunity to Acquisition: Payloop Technologies',
    summary: 'A technical co-founder and a design lead met on Opportunity Network, built a payments API, and exited to a larger fintech in 18 months.',
    teamFormed: 'Sam Okafor (CTO) and Maya Chen (Design Lead) connected through a technology opportunity posting.',
    opportunityDiscovered: 'A fintech startup needed a technical co-founder to build a payments API platform from scratch.',
    ventureLaunched: 'Payloop launched its API in 4 months, onboarded 12 fintech clients, and processed $50M in transactions.',
    businessGrowth: 'Acquired by a larger fintech for an undisclosed sum. Both founders moved into leadership roles at the acquiring company.',
    imageUrl: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=600',
    publishedAt: '2026-06-15',
    participantIds: ['p-sam', 'p-maya'],
    industry: 'Technology',
  },
  {
    id: 'ss-2',
    title: 'Bright & Co Cleaning: From 2 Clients to 30',
    summary: 'An operations lead and an investor partnered to scale a cleaning business from 2 to 30 recurring clients in one year.',
    teamFormed: 'Priya Patel (Operations Lead) and Jordan Reyes (Investor) partnered after connecting through a service business opportunity.',
    opportunityDiscovered: 'A cleaning business needed an operations partner to scale beyond its initial 2 recurring clients.',
    ventureLaunched: 'Bright & Co launched with a systematic hiring pipeline, QA checklists, and a referral program.',
    businessGrowth: 'Grew from 2 to 30 recurring clients in 12 months, hired 4 staff members, and achieved 90% retention.',
    imageUrl: 'https://images.pexels.com/photos/4239035/pexels-photo-4239035.jpeg?auto=compress&cs=tinysrgb&w=600',
    publishedAt: '2026-05-20',
    participantIds: ['p-priya', 'p-jordan'],
    industry: 'Cleaning & Services',
  },
  {
    id: 'ss-3',
    title: 'East Austin Bungalow: A Profitable Partnership',
    summary: 'A project manager and an investor flipped a 1950s bungalow in 4 months, achieving a 22% return on investment.',
    teamFormed: 'Demo User (Project Manager) and Jordan Reyes (Lead Investor) partnered on a real estate flip opportunity.',
    opportunityDiscovered: 'A neglected bungalow in East Austin presented a renovation and resale opportunity.',
    ventureLaunched: 'Acquired the property, completed renovations in 4 months with a licensed contractor, and listed for sale.',
    businessGrowth: 'Sold at 22% ROI above acquisition plus renovation costs. Both partners reinvested in a second property.',
    imageUrl: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=600',
    publishedAt: '2026-04-10',
    participantIds: ['p-me', 'p-jordan'],
    industry: 'Real Estate',
  },
];

export const RESOURCE_ARTICLES: ResourceArticle[] = [
  {
    id: 'ra-1',
    title: 'How to Find a Business Partner',
    slug: 'how-to-find-a-business-partner',
    category: 'Finding Partners',
    excerpt: 'A practical guide to finding the right co-founder or collaborator for your venture — from defining what you need to vetting for trust.',
    content: 'Finding the right business partner is the single most important decision you will make for your venture. Here is a framework for doing it well.\n\n## 1. Define What You Need\n\nBefore looking for a partner, get specific about the gap. Do you need capital, operations, technical skills, or domain expertise? Write down the 3 things you cannot do alone.\n\n## 2. Look in the Right Places\n\nOpportunity Network is built for this. Post an opportunity describing what you bring and what you need. Browse builder profiles. Filter by skills, industry, and availability.\n\n## 3. Vetting for Trust\n\nBefore committing, verify identity, employment, and venture participation. Ask for references from past collaborators. Look at venture history.\n\n## 4. Start Small\n\nBefore signing an equity agreement, work on a small project together. A 2-week trial reveals more than 2 months of interviews.\n\n## 5. Structure the Partnership\n\nUse a lawyer to draft your agreement. Define equity splits, roles, decision-making, and exit terms upfront.',
    readTime: '6 min read',
    publishedAt: '2026-06-01',
    authorName: 'Opportunity Network Team',
  },
  {
    id: 'ra-2',
    title: 'How to Start a Startup',
    slug: 'how-to-start-a-startup',
    category: 'Starting Up',
    excerpt: 'A step-by-step checklist for going from idea to launched startup — covering validation, formation, team, and first revenue.',
    content: 'Starting a startup is less about the idea and more about execution. Here is the path from zero to launched.\n\n## 1. Validate the Problem\n\nTalk to 20 potential customers. If you cannot find 10 people who feel the pain acutely, the problem may not be big enough.\n\n## 2. Form the Entity\n\nSet up an LLC or C-Corp depending on your funding path. Use a lawyer or a service like LegalZoom. Get an EIN.\n\n## 3. Build the Team\n\nFind a co-founder who complements your skills. Post on Opportunity Network. Look for trust signals: verified identity, venture history, references.\n\n## 4. Build an MVP\n\nShip the smallest version of the product that solves the core problem. It should take 4-8 weeks, not 4-8 months.\n\n## 5. Get First Revenue\n\nCharge from day one. Even $10 proves someone values what you built.',
    readTime: '8 min read',
    publishedAt: '2026-05-20',
    authorName: 'Opportunity Network Team',
  },
  {
    id: 'ra-3',
    title: 'Startup Checklist: Everything You Need Before Launch',
    slug: 'startup-checklist',
    category: 'Checklists',
    excerpt: 'A comprehensive checklist covering legal, financial, technical, and marketing tasks every startup should complete before launching.',
    content: 'Use this checklist to make sure nothing falls through the cracks before launch.\n\n## Legal\n- [ ] Entity formed (LLC or C-Corp)\n- [ ] EIN obtained\n- [ ] Operating agreement or bylaws signed\n- [ ] Trademark filed (if applicable)\n- [ ] Privacy policy and terms of service drafted\n\n## Financial\n- [ ] Business bank account opened\n- [ ] Bookkeeping system set up\n- [ ] Tax strategy in place\n- [ ] Runway calculated (minimum 6 months)\n\n## Technical\n- [ ] Domain purchased\n- [ ] Website deployed\n- [ ] Analytics installed\n- [ ] Error monitoring set up\n\n## Marketing\n- [ ] Brand identity finalized\n- [ ] Landing page live\n- [ ] Email list started\n- [ ] Social profiles created',
    readTime: '5 min read',
    publishedAt: '2026-05-10',
    authorName: 'Opportunity Network Team',
  },
  {
    id: 'ra-4',
    title: 'Business Formation Guide: LLC vs C-Corp vs S-Corp',
    slug: 'business-formation-guide',
    category: 'Business Formation',
    excerpt: 'A plain-English comparison of the three most common business entity types, and how to choose the right one for your venture.',
    content: 'Choosing the right entity type affects your taxes, liability, and ability to raise funding. Here is the breakdown.\n\n## LLC (Limited Liability Company)\n\nBest for: Small businesses, service companies, real estate.\nPros: Simple, flexible, pass-through taxation.\nCons: Harder to raise venture funding.\n\n## C-Corp\n\nBest for: Startups planning to raise venture capital or go public.\nPros: Preferred by investors, easy to issue stock, no pass-through limits.\nCons: Double taxation, more paperwork.\n\n## S-Corp\n\nBest for: Small businesses that want pass-through taxation with some corporate structure.\nPros: Pass-through, no double taxation.\nCons: Limits on number of shareholders, one class of stock only.\n\n## How to Choose\n\nIf you plan to raise VC funding, choose C-Corp. If you are building a service business or real estate venture, choose LLC. Talk to a CPA before deciding.',
    readTime: '7 min read',
    publishedAt: '2026-04-28',
    authorName: 'Opportunity Network Team',
  },
  {
    id: 'ra-5',
    title: 'Real Estate Investing Guide: From First Property to Portfolio',
    slug: 'real-estate-investing-guide',
    category: 'Real Estate Investing',
    excerpt: 'A beginner-to-intermediate guide to real estate investing — covering flips, rentals, partnerships, and financing.',
    content: 'Real estate is one of the most accessible paths to building wealth. Here is how to start.\n\n## 1. Flipping\n\nBuy, renovate, sell. Best for those with construction knowledge or a partner who has it. Target 15-25% ROI after costs.\n\n## 2. Rentals\n\nBuy, hold, rent. Cash flow plus appreciation. Best for those who want passive income. Screen tenants carefully.\n\n## 3. Partnerships\n\nMost real estate deals require multiple skill sets: capital, construction, property management. Find partners on Opportunity Network who complement yours.\n\n## 4. Financing\n\nOptions: conventional mortgage, hard money loan, private money, seller financing. Start with conventional if you have good credit and 20% down.',
    readTime: '9 min read',
    publishedAt: '2026-04-15',
    authorName: 'Opportunity Network Team',
  },
  {
    id: 'ra-6',
    title: 'Grant Resources: A Complete Guide to Finding and Winning Grants',
    slug: 'grant-resources',
    category: 'Grant Resources',
    excerpt: 'Everything you need to know about grants — where to find them, how to write a winning application, and common mistakes to avoid.',
    content: 'Grants are non-dilutive funding that can transform a nonprofit or early-stage venture. Here is the complete guide.\n\n## 1. Where to Find Grants\n\n- Grants.gov (federal)\n- Foundation Directory Online\n- Community foundations in your area\n- Corporate giving programs\n\n## 2. How to Write a Winning Application\n\n- Read the guidelines twice. Most rejections are for not following instructions.\n- Tell a story with data. Funders want impact, not just need.\n- Be specific about outcomes. What will change because of this grant?\n\n## 3. Common Mistakes\n\n- Vague budgets\n- No letters of support\n- Applying to the wrong funder\n- Missing the deadline\n\n## 4. Working with a Grant Writer\n\nA professional grant writer can increase your win rate significantly. Find verified grant writers on Opportunity Network.',
    readTime: '8 min read',
    publishedAt: '2026-03-30',
    authorName: 'Opportunity Network Team',
  },
];

export function getProfessional(id: ID): Professional | undefined {
  return PROFESSIONALS.find((p) => p.id === id);
}

export function getCompany(id: ID): Company | undefined {
  return COMPANIES.find((c) => c.id === id);
}

export function getResourceBySlug(slug: string): ResourceArticle | undefined {
  return RESOURCE_ARTICLES.find((a) => a.slug === slug);
}
