import type {
  Profile,
  CollaborationGroup,
  Opportunity,
  CollaborationSpace,
  Conversation,
  AppNotification,
  TrustState,
  Skill,
  ID,
} from './types';

export const SKILLS: Skill[] = [
  { id: 'sk-contracting', name: 'General Contracting', category: 'Real Estate' },
  { id: 'sk-financial-partner', name: 'Financial Partner', category: 'Finance' },
  { id: 'sk-ops', name: 'Operations Management', category: 'Business' },
  { id: 'sk-grant-writing', name: 'Grant Writing', category: 'Nonprofit' },
  { id: 'sk-fundraising', name: 'Fundraising', category: 'Nonprofit' },
  { id: 'sk-ux', name: 'UX Design', category: 'Technology' },
  { id: 'sk-frontend', name: 'Frontend Development', category: 'Technology' },
  { id: 'sk-backend', name: 'Backend Development', category: 'Technology' },
  { id: 'sk-marketing', name: 'Marketing', category: 'Business' },
  { id: 'sk-producer', name: 'Film Production', category: 'Film & Media' },
  { id: 'sk-editor', name: 'Video Editing', category: 'Film & Media' },
  { id: 'sk-cinematography', name: 'Cinematography', category: 'Film & Media' },
  { id: 'sk-ecommerce', name: 'E-commerce Operations', category: 'E-commerce' },
  { id: 'sk-ads', name: 'Paid Advertising', category: 'Marketing' },
  { id: 'sk-real-estate', name: 'Real Estate Analysis', category: 'Real Estate' },
  { id: 'sk-project-mgmt', name: 'Project Management', category: 'Business' },
  { id: 'sk-cleaning-ops', name: 'Cleaning Operations', category: 'Cleaning & Services' },
  { id: 'sk-chef', name: 'Culinary Operations', category: 'Food & Restaurant' },
  { id: 'sk-legal-ops', name: 'Legal Operations', category: 'Business' },
  { id: 'sk-sales', name: 'Sales', category: 'Business' },
];

const v = (type: VerificationClaim['type'], state: VerificationClaim['state'], label: string, detail?: string): VerificationClaim =>
  ({ id: `v-${type}-${Math.random().toString(36).slice(2, 7)}`, type, state, label, detail, verifiedAt: state === 'verified' ? '2026-03-12' : undefined });

import type { VerificationClaim } from './types';

export const PROFILES: Profile[] = [
  {
    id: 'p-me',
    name: 'You (Demo User)',
    photoUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Austin, TX',
    headline: 'Product builder & collaboration lead',
    bio: 'I build products and teams. I care about trust, transparency, and shipping real things with people I respect.',
    skills: ['Project Management', 'UX Design', 'Frontend Development', 'Operations Management'],
    interests: ['Startups', 'Real estate', 'Community projects'],
    industries: ['Technology', 'Real Estate', 'Community'],
    availability: 'Available',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['A real estate partner project', 'A community initiative to co-lead'],
    buildingIds: ['cs-flip', 'cs-doc'],
    ventureHistory: [
      { id: 'vh1', title: 'SaaS onboarding redesign', role: 'Lead', outcome: 'Completed', visibility: 'public', year: 2024, industry: 'Technology', summary: 'Led a 4-person team to rebuild onboarding; shipped in 3 months.' },
      { id: 'vh2', title: 'Rental property renovation', role: 'Project Manager', outcome: 'Operating', visibility: 'profile', year: 2023, industry: 'Real Estate', summary: 'Co-managed a full duplex renovation and lease-up.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-maya', count: 3, summary: 'Worked together on three product builds.' },
      { partnerId: 'p-jordan', count: 2, summary: 'Two real estate renovations.' },
    ],
    rolesHeld: ['Project Manager', 'Product Lead', 'Co-founder'],
    endorsements: [
      { fromId: 'p-maya', text: 'Clear communicator who keeps projects moving.', skill: 'Project Management' },
      { fromId: 'p-jordan', text: 'Honest and organized — a great partner on renovations.', skill: 'Real Estate Analysis' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified', 'ID document checked'),
      v('employment', 'pending', 'Employment verification', 'In review'),
      v('venture_participation', 'verified', 'Venture participation verified', '2 prior ventures confirmed'),
    ],
    communityStanding: 'positive',
  },
  {
    id: 'p-maya',
    name: 'Maya Chen',
    photoUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Remote (Denver, CO)',
    headline: 'Senior product designer & design lead',
    bio: 'Designer who has shipped 12 products end-to-end. I prefer async, mission-driven teams with clear ownership.',
    skills: ['UX Design', 'Frontend Development', 'Project Management', 'Marketing'],
    interests: ['Design systems', 'Education', 'Nonprofits'],
    industries: ['Technology', 'Nonprofit', 'Creative'],
    availability: 'Available',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['Design lead for a meaningful product', 'Nonprofit design partnership'],
    buildingIds: ['cs-tech'],
    ventureHistory: [
      { id: 'vh3', title: 'Fintech mobile app', role: 'Design Lead', outcome: 'Launched', visibility: 'public', year: 2024, industry: 'Technology', summary: 'Led design from concept to launch.' },
      { id: 'vh4', title: 'Nonprofit donor portal', role: 'Designer', outcome: 'Completed', visibility: 'public', year: 2023, industry: 'Nonprofit', summary: 'Pro-bono redesign.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-me', count: 3, summary: 'Three product builds together.' },
      { partnerId: 'p-sam', count: 2, summary: 'Two design+dev collaborations.' },
    ],
    rolesHeld: ['Design Lead', 'Senior Designer', 'Advisor'],
    endorsements: [
      { fromId: 'p-me', text: 'Outstanding design judgment and follow-through.', skill: 'UX Design' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('employment', 'verified', 'Employment verified', 'Senior Designer at Northwind'),
      v('education', 'verified', 'Education verified', 'BFA, RISD'),
      v('certification', 'pending', 'Certification verification', 'Pending: Nielsen Norman UX Cert'),
    ],
    communityStanding: 'positive',
  },
  {
    id: 'p-jordan',
    name: 'Jordan Reyes',
    photoUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Phoenix, AZ',
    headline: 'Real estate investor & contractor liaison',
    bio: 'I flip 2-3 houses a year and invest in small service businesses. Looking for partners who bring capital or operations.',
    skills: ['Real Estate Analysis', 'General Contracting', 'Project Management'],
    interests: ['House flipping', 'Small business acquisition'],
    industries: ['Real Estate', 'Cleaning & Services'],
    availability: 'Limited',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['Financial partner for next flip', 'Operations partner for cleaning business'],
    buildingIds: ['cs-flip'],
    ventureHistory: [
      { id: 'vh5', title: 'Eastside duplex flip', role: 'Lead', outcome: 'Sold', visibility: 'public', year: 2024, industry: 'Real Estate', summary: 'Bought, renovated, sold in 7 months.' },
      { id: 'vh6', title: 'Downtown triplex renovation', role: 'Project Manager', outcome: 'Operating', visibility: 'profile', year: 2023, industry: 'Real Estate', summary: 'Renovated and now renting.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-me', count: 2, summary: 'Two renovations together.' },
      { partnerId: 'p-priya', count: 1, summary: 'One cleaning business launch.' },
    ],
    rolesHeld: ['Lead Investor', 'Project Manager', 'Operations Advisor'],
    endorsements: [
      { fromId: 'p-me', text: 'Knows the numbers and the field — a rare combo.', skill: 'Real Estate Analysis' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('business_ownership', 'verified', 'Business ownership verified', 'Reyes Holdings LLC'),
      v('venture_participation', 'verified', 'Venture participation verified', '5 flips confirmed'),
    ],
    communityStanding: 'positive',
  },
  {
    id: 'p-priya',
    name: 'Priya Patel',
    photoUrl: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Austin, TX',
    headline: 'Operations partner for service businesses',
    bio: 'I run day-to-day operations for cleaning and service businesses. I love systems, scheduling, and hiring.',
    skills: ['Operations Management', 'Cleaning Operations', 'Sales', 'Project Management'],
    interests: ['Service businesses', 'Hiring', 'Systems design'],
    industries: ['Cleaning & Services', 'E-commerce'],
    availability: 'Available',
    timeCommitment: 'Full-time',
    opportunitiesSought: ['Operations lead for a growing service business', 'E-commerce ops partner'],
    buildingIds: ['cs-clean'],
    ventureHistory: [
      { id: 'vh7', title: 'Bright & Co Cleaning', role: 'Operations Lead', outcome: 'Operating', visibility: 'public', year: 2024, industry: 'Cleaning & Services', summary: 'Grew from 2 to 12 clients in a year.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-jordan', count: 1, summary: 'Launched a cleaning business together.' },
      { partnerId: 'p-marcus', count: 2, summary: 'Two service business ops roles.' },
    ],
    rolesHeld: ['Operations Lead', 'General Manager'],
    endorsements: [
      { fromId: 'p-jordan', text: 'Reliable and detail-oriented. Runs a tight operation.', skill: 'Operations Management' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('employment', 'unverified', 'Employment verification', 'Not yet started'),
      v('venture_participation', 'verified', 'Venture participation verified', '1 venture confirmed'),
    ],
    communityStanding: 'positive',
  },
  {
    id: 'p-sam',
    name: 'Sam Okafor',
    photoUrl: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Remote (Lagos, NG)',
    headline: 'Full-stack engineer & technical co-founder',
    bio: 'I build the whole stack. I prefer small, senior teams and clear product ownership.',
    skills: ['Frontend Development', 'Backend Development', 'Project Management'],
    interests: ['Startups', 'Developer tools', 'Fintech'],
    industries: ['Technology', 'Finance'],
    availability: 'Available',
    timeCommitment: 'Full-time',
    opportunitiesSought: ['Technical co-founder role', 'Fintech build'],
    buildingIds: ['cs-tech'],
    ventureHistory: [
      { id: 'vh8', title: 'Payments API platform', role: 'CTO', outcome: 'Acquired', visibility: 'public', year: 2023, industry: 'Technology', summary: 'Co-founded, built, and exited to a larger fintech.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-maya', count: 2, summary: 'Two design+dev collaborations.' },
    ],
    rolesHeld: ['CTO', 'Lead Engineer', 'Technical Co-founder'],
    endorsements: [
      { fromId: 'p-maya', text: 'One of the clearest technical thinkers I have worked with.', skill: 'Backend Development' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('employment', 'verified', 'Employment verified', 'Former CTO at Payloop'),
      v('venture_participation', 'verified', 'Venture participation verified', 'Acquisition confirmed'),
    ],
    communityStanding: 'positive',
  },
  {
    id: 'p-marcus',
    name: 'Marcus Webb',
    photoUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Brooklyn, NY',
    headline: 'Documentary producer & editor',
    bio: 'I produce and edit long-form documentary work. Looking for partners on impact-driven stories.',
    skills: ['Film Production', 'Video Editing', 'Cinematography', 'Project Management'],
    interests: ['Documentary', 'Social impact', 'Climate'],
    industries: ['Film & Media', 'Nonprofit', 'Creative'],
    availability: 'Limited',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['Producer partner for climate documentary', 'Editor for short-form series'],
    buildingIds: ['cs-doc'],
    ventureHistory: [
      { id: 'vh9', title: 'Coastlines (feature doc)', role: 'Producer/Editor', outcome: 'Completed', visibility: 'public', year: 2024, industry: 'Film & Media', summary: 'Festival-circuit climate documentary.' },
    ],
    collaborationHistory: [
      { partnerId: 'p-priya', count: 2, summary: 'Two service business ops roles.' },
      { partnerId: 'p-me', count: 1, summary: 'One documentary co-production.' },
    ],
    rolesHeld: ['Producer', 'Editor', 'Director'],
    endorsements: [
      { fromId: 'p-me', text: 'Brings stories home on time and on budget.', skill: 'Film Production' },
    ],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('employment', 'could_not_verify', 'Employment verification', 'Claim could not be verified'),
      v('certification', 'unverified', 'Certification verification', 'Not yet started'),
    ],
    communityStanding: 'neutral',
  },
  {
    id: 'p-elena',
    name: 'Elena Rossi',
    photoUrl: 'https://images.pexels.com/photos/139827/pexels-photo-139827.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Remote (Milan, IT)',
    headline: 'E-commerce growth & marketing partner',
    bio: 'I scale D2C brands from first sale to seven figures. Paid ads, lifecycle, and ops.',
    skills: ['Marketing', 'Paid Advertising', 'E-commerce Operations', 'Sales'],
    interests: ['D2C', 'Sustainable goods', 'Marketplaces'],
    industries: ['E-commerce', 'Creative'],
    availability: 'Available',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['Marketing partner for a growing D2C brand', 'E-commerce ops co-lead'],
    buildingIds: [],
    ventureHistory: [
      { id: 'vh10', title: 'Linen home goods brand', role: 'Growth Lead', outcome: 'Operating', visibility: 'public', year: 2024, industry: 'E-commerce', summary: 'Scaled to $1.2M ARR in 14 months.' },
    ],
    collaborationHistory: [],
    rolesHeld: ['Growth Lead', 'Head of Marketing'],
    endorsements: [],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'pending', 'Identity verification', 'In review'),
      v('employment', 'unverified', 'Employment verification', 'Not yet started'),
    ],
    communityStanding: 'neutral',
  },
  {
    id: 'p-david',
    name: 'David Kim',
    photoUrl: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=200',
    location: 'Seattle, WA',
    headline: 'Grant writer & nonprofit strategy',
    bio: 'I have written 40+ funded grants. I partner with mission-driven teams on funding strategy.',
    skills: ['Grant Writing', 'Fundraising', 'Project Management'],
    interests: ['Nonprofits', 'Education', 'Community'],
    industries: ['Nonprofit', 'Community'],
    availability: 'Available',
    timeCommitment: 'Part-time',
    opportunitiesSought: ['Grant writer for a nonprofit', 'Fundraising co-lead'],
    buildingIds: [],
    ventureHistory: [
      { id: 'vh11', title: 'Community literacy initiative', role: 'Grant Writer', outcome: 'Completed', visibility: 'public', year: 2024, industry: 'Nonprofit', summary: 'Secured $480K in funding.' },
    ],
    collaborationHistory: [],
    rolesHeld: ['Grant Writer', 'Development Consultant'],
    endorsements: [],
    verifications: [
      v('email', 'verified', 'Email verified'),
      v('phone', 'verified', 'Phone verified'),
      v('identity', 'verified', 'Identity verified'),
      v('certification', 'verified', 'Certification verified', 'CFRE certified'),
      v('reference', 'verified', 'Reference verified', '2 references confirmed'),
    ],
    communityStanding: 'positive',
  },
];

export const GROUPS: CollaborationGroup[] = [
  {
    id: 'g-maya-sam',
    kind: 'pair',
    name: 'Maya & Sam',
    memberIds: ['p-maya', 'p-sam'],
    combinedSkills: ['UX Design', 'Frontend Development', 'Backend Development', 'Project Management'],
    industries: ['Technology'],
    venturesCompletedTogether: 2,
    activeVentures: 1,
    historyLengthMonths: 18,
    availabilityGroup: 'Available',
    availabilityIndividual: { 'p-maya': 'Available', 'p-sam': 'Available' },
    matchReasons: ['Proven collaboration history on 2 shipped products', 'Covers full design+engineering stack', 'Both available part-time'],
  },
  {
    id: 'g-trio',
    kind: 'group',
    name: 'Austin Build Crew',
    memberIds: ['p-maya', 'p-sam', 'p-me'],
    combinedSkills: ['UX Design', 'Frontend Development', 'Backend Development', 'Project Management', 'Operations Management'],
    industries: ['Technology', 'Community'],
    venturesCompletedTogether: 3,
    activeVentures: 1,
    historyLengthMonths: 24,
    availabilityGroup: 'Limited',
    availabilityIndividual: { 'p-maya': 'Available', 'p-sam': 'Available', 'p-me': 'Available' },
    matchReasons: ['Established working relationship across 3 ventures', 'Covers design, engineering, and ops', 'History of meeting deadlines'],
  },
  {
    id: 'g-flip-team',
    kind: 'team',
    name: 'Reyes Renovation Team',
    memberIds: ['p-jordan', 'p-priya', 'p-me'],
    combinedSkills: ['Real Estate Analysis', 'General Contracting', 'Operations Management', 'Project Management'],
    industries: ['Real Estate', 'Cleaning & Services'],
    venturesCompletedTogether: 2,
    activeVentures: 1,
    historyLengthMonths: 14,
    availabilityGroup: 'Available',
    availabilityIndividual: { 'p-jordan': 'Limited', 'p-priya': 'Available', 'p-me': 'Available' },
    matchReasons: ['Verified project history on 2 flips', 'Covers acquisition, contracting, and ops', 'Available as a group'],
  },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'o-flip',
    title: 'House-flipping partnership — Bungalow in East Austin',
    description:
      'We have a property under contract in East Austin and a renovation scope defined. We need a licensed contractor to lead the build and a financial partner to share equity on the project.',
    category: 'Real Estate',
    stage: 'Recruiting',
    goals: ['Complete renovation in 5 months', 'List and sell within 7 months total', 'Target 18%+ return on capital'],
    location: 'Austin, TX',
    remote: false,
    timeCommitment: 'Part-time',
    roles: [
      { id: 'r1', title: 'Lead Contractor', skillsNeeded: ['General Contracting'], openPositions: 1, compensation: 'Paid', filled: 0 },
      { id: 'r2', title: 'Financial Partner', skillsNeeded: ['Financial Partner'], openPositions: 1, compensation: 'Partnership', filled: 0 },
    ],
    skillsNeeded: ['General Contracting', 'Financial Partner', 'Real Estate Analysis'],
    creatorBrings: 'Property under contract, renovation scope, and project management.',
    compensation: 'Partnership',
    accepts: 'both',
    startDate: '2026-09-01',
    visibility: 'public',
    postedDate: '2026-07-15',
    teamSize: 2,
    verified: true,
    ownerId: 'p-jordan',
    dna: {
      industry: 'Real Estate',
      stage: 'Recruiting',
      requiredSkills: ['General Contracting', 'Financial Partner'],
      optionalSkills: ['Real Estate Analysis'],
      timeCommitment: 'Part-time',
      locationPreference: 'On-site',
      workStyle: 'On-site',
      riskTolerance: 'High',
      leadershipNeeds: 'Co-lead',
      collaborationStyle: 'Hierarchical',
      missionDrive: 'Profit-driven',
      fundingStatus: 'Seeking funding',
    },
    matchReasons: ['You have verified experience in real estate', 'You have completed 2 similar renovations', 'Available during the requested schedule'],
  },
  {
    id: 'o-clean',
    title: 'Operations partner for a growing cleaning business',
    description:
      'Bright & Co Cleaning has 12 recurring clients and 3 staff. I am looking for an operations partner to co-own scheduling, hiring, and quality control in exchange for equity.',
    category: 'Cleaning & Services',
    stage: 'Growing',
    goals: ['Reach 30 recurring clients in 12 months', 'Build a hiring pipeline', 'Standardize QA checklists'],
    location: 'Austin, TX',
    remote: false,
    timeCommitment: 'Full-time',
    roles: [
      { id: 'r3', title: 'Operations Partner', skillsNeeded: ['Operations Management', 'Cleaning Operations'], openPositions: 1, compensation: 'Equity', filled: 0 },
    ],
    skillsNeeded: ['Operations Management', 'Cleaning Operations', 'Sales'],
    creatorBrings: 'Client base, brand, equipment, and 3 trained staff.',
    compensation: 'Equity',
    accepts: 'individuals',
    startDate: '2026-08-15',
    visibility: 'public',
    postedDate: '2026-07-10',
    teamSize: 1,
    verified: true,
    ownerId: 'p-priya',
    dna: {
      industry: 'Cleaning & Services',
      stage: 'Growing',
      requiredSkills: ['Operations Management', 'Cleaning Operations'],
      optionalSkills: ['Sales'],
      timeCommitment: 'Full-time',
      locationPreference: 'On-site',
      workStyle: 'On-site',
      riskTolerance: 'Medium',
      leadershipNeeds: 'Co-lead',
      collaborationStyle: 'Flat',
      missionDrive: 'Balanced',
      fundingStatus: 'Self-funded',
    },
    matchReasons: ['You have operations management experience', 'Available full-time', 'Verified venture participation'],
  },
  {
    id: 'o-nonprofit',
    title: 'Grant writer for youth literacy nonprofit',
    description:
      'Read Together is a small nonprofit serving 200 students. We need an experienced grant writer to lead our fall funding push.',
    category: 'Nonprofit',
    stage: 'Recruiting',
    goals: ['Secure $250K in grant funding', 'Build a 12-month funding calendar', 'Train staff on grant reporting'],
    location: 'Remote',
    remote: true,
    timeCommitment: 'Light',
    roles: [
      { id: 'r4', title: 'Grant Writer', skillsNeeded: ['Grant Writing'], openPositions: 1, compensation: 'Paid', filled: 0 },
    ],
    skillsNeeded: ['Grant Writing', 'Fundraising'],
    creatorBrings: 'Programs, outcomes data, and 501(c)(3) status.',
    compensation: 'Paid',
    accepts: 'individuals',
    startDate: '2026-09-01',
    visibility: 'public',
    postedDate: '2026-07-18',
    teamSize: 3,
    verified: true,
    ownerId: 'p-david',
    dna: {
      industry: 'Nonprofit',
      stage: 'Recruiting',
      requiredSkills: ['Grant Writing'],
      optionalSkills: ['Fundraising'],
      timeCommitment: 'Light',
      locationPreference: 'Remote',
      workStyle: 'Async',
      riskTolerance: 'Low',
      leadershipNeeds: 'Contributor',
      collaborationStyle: 'Self-directed',
      missionDrive: 'Mission-driven',
      fundingStatus: 'Seeking funding',
    },
    matchReasons: ['Mission-driven match', 'Remote and async compatible', 'Light time commitment fits your availability'],
  },
  {
    id: 'o-tech',
    title: 'Designer + developer for a fintech onboarding product',
    description:
      'We are building a guided onboarding flow for a new consumer fintech app. We need a design lead and a frontend engineer to own the flow end-to-end.',
    category: 'Technology',
    stage: 'Building',
    goals: ['Ship onboarding v1 in 8 weeks', 'Reach 70% onboarding completion', 'Establish a reusable design system'],
    location: 'Remote',
    remote: true,
    timeCommitment: 'Part-time',
    roles: [
      { id: 'r5', title: 'Design Lead', skillsNeeded: ['UX Design'], openPositions: 1, compensation: 'Equity', filled: 0 },
      { id: 'r6', title: 'Frontend Engineer', skillsNeeded: ['Frontend Development'], openPositions: 1, compensation: 'Equity', filled: 0 },
    ],
    skillsNeeded: ['UX Design', 'Frontend Development', 'Backend Development'],
    creatorBrings: 'Product strategy, backend API, and initial designs.',
    compensation: 'Equity',
    accepts: 'both',
    startDate: '2026-08-01',
    visibility: 'public',
    postedDate: '2026-07-05',
    teamSize: 2,
    verified: true,
    ownerId: 'p-sam',
    dna: {
      industry: 'Technology',
      stage: 'Building',
      requiredSkills: ['UX Design', 'Frontend Development'],
      optionalSkills: ['Backend Development'],
      timeCommitment: 'Part-time',
      locationPreference: 'Remote',
      workStyle: 'Async',
      riskTolerance: 'Medium',
      leadershipNeeds: 'Co-lead',
      collaborationStyle: 'Flat',
      missionDrive: 'Balanced',
      fundingStatus: 'Bootstrapped',
    },
    matchReasons: ['Matches your UX and frontend skills', 'Async remote work style matches', 'You have shipped 2 similar products'],
  },
  {
    id: 'o-doc',
    title: 'Producer + editor for a climate documentary short',
    description:
      'We have 40 hours of footage for a 20-minute climate documentary short. We need a producer to structure the story and an editor to lead the cut.',
    category: 'Film & Media',
    stage: 'Planning',
    goals: ['Picture lock in 12 weeks', 'Submit to 3 festivals', 'Deliver a 20-minute cut'],
    location: 'Brooklyn, NY',
    remote: false,
    timeCommitment: 'Part-time',
    roles: [
      { id: 'r7', title: 'Producer', skillsNeeded: ['Film Production'], openPositions: 1, compensation: 'Negotiable', filled: 0 },
      { id: 'r8', title: 'Editor', skillsNeeded: ['Video Editing'], openPositions: 1, compensation: 'Negotiable', filled: 0 },
    ],
    skillsNeeded: ['Film Production', 'Video Editing', 'Cinematography'],
    creatorBrings: 'Footage, subject access, and festival contacts.',
    compensation: 'Negotiable',
    accepts: 'both',
    startDate: '2026-09-15',
    visibility: 'public',
    postedDate: '2026-07-20',
    teamSize: 1,
    verified: false,
    ownerId: 'p-marcus',
    dna: {
      industry: 'Film & Media',
      stage: 'Planning',
      requiredSkills: ['Film Production', 'Video Editing'],
      optionalSkills: ['Cinematography'],
      timeCommitment: 'Part-time',
      locationPreference: 'On-site',
      workStyle: 'Synchronous',
      riskTolerance: 'Medium',
      leadershipNeeds: 'Co-lead',
      collaborationStyle: 'Consensus',
      missionDrive: 'Mission-driven',
      fundingStatus: 'Self-funded',
    },
    matchReasons: ['You co-produced a prior documentary', 'Available during the requested schedule', 'Mission-driven match'],
  },
  {
    id: 'o-ecom',
    title: 'Marketing partner for a sustainable home goods D2C brand',
    description:
      'Linen & Co is a sustainable home goods brand at $40K/mo. We need a marketing partner to own paid acquisition and lifecycle in exchange for equity.',
    category: 'E-commerce',
    stage: 'Growing',
    goals: ['Reach $100K/mo in 9 months', 'Build a profitable paid acquisition engine', 'Launch lifecycle email program'],
    location: 'Remote',
    remote: true,
    timeCommitment: 'Part-time',
    roles: [
      { id: 'r9', title: 'Growth Marketing Partner', skillsNeeded: ['Marketing', 'Paid Advertising'], openPositions: 1, compensation: 'Equity', filled: 0 },
    ],
    skillsNeeded: ['Marketing', 'Paid Advertising', 'E-commerce Operations'],
    creatorBrings: 'Brand, product, supply chain, and 1,200 customers.',
    compensation: 'Equity',
    accepts: 'individuals',
    startDate: '2026-08-15',
    visibility: 'public',
    postedDate: '2026-07-12',
    teamSize: 1,
    verified: false,
    ownerId: 'p-elena',
    dna: {
      industry: 'E-commerce',
      stage: 'Growing',
      requiredSkills: ['Marketing', 'Paid Advertising'],
      optionalSkills: ['E-commerce Operations'],
      timeCommitment: 'Part-time',
      locationPreference: 'Remote',
      workStyle: 'Async',
      riskTolerance: 'Medium',
      leadershipNeeds: 'Co-lead',
      collaborationStyle: 'Flat',
      missionDrive: 'Balanced',
      fundingStatus: 'Self-funded',
    },
    matchReasons: ['Matches your marketing skills', 'Remote async work style', 'Growing stage fits your availability'],
  },
];

const baseModules = (extra: { kind: import('./types').ModuleKind; label: string }[]) => {
  const core: { kind: import('./types').ModuleKind; label: string }[] = [
    { kind: 'team_chat', label: 'Team Chat' },
    { kind: 'tasks', label: 'Tasks' },
    { kind: 'milestones', label: 'Milestones' },
    { kind: 'decision_log', label: 'Decision Log' },
    { kind: 'collaboration_record', label: 'Collaboration Record' },
    { kind: 'notes', label: 'Notes' },
    { kind: 'files', label: 'Files' },
    { kind: 'calendar', label: 'Calendar' },
    { kind: 'project_timeline', label: 'Project Timeline' },
  ];
  const all = [...core, ...extra];
  return all.map((m, i) => ({ kind: m.kind, label: m.label, pinned: i < 4, visible: true, order: i }));
};

export const SPACES: CollaborationSpace[] = [
  {
    id: 'cs-flip',
    opportunityId: 'o-flip',
    name: 'East Austin Bungalow Flip',
    description: 'Renovation and sale of a 1,200 sqft bungalow. Acquisition done; renovation in progress.',
    mission: 'Revitalize a neglected East Austin property while delivering a strong return for investors and improving the neighborhood.',
    successDefinition: 'Renovation completed on budget, property sold at or above target price, all partners satisfied with returns.',
    memberIds: ['p-me', 'p-jordan'],
    roles: { 'p-me': 'Project Manager', 'p-jordan': 'Lead Investor' },
    tasks: [
      {
        id: 't1',
        title: 'Finalize renovation scope document',
        description: 'Lock the scope of work for kitchen, bath, and flooring.',
        ownerId: 'p-me',
        reviewerId: 'p-jordan',
        dueDate: '2026-07-25',
        priority: 'High',
        status: 'Ready for review',
        checklist: [
          { id: 'c1', text: 'Draft scope', done: true },
          { id: 'c2', text: 'Add material list', done: true },
          { id: 'c3', text: 'Add budget breakdown', done: true, submittedForReview: true },
          { id: 'c4', text: 'Get contractor sign-off', done: false },
        ],
        dependencies: [],
        comments: [{ id: 'cm1', authorId: 'p-jordan', text: 'Looks thorough. Approving pending one question on flooring.', at: '2026-07-22' }],
        revisions: [{ version: 1, at: '2026-07-21', by: 'p-me', note: 'Initial submission', status: 'Ready for review' }],
      },
      {
        id: 't2',
        title: 'Line up 3 contractor bids',
        description: 'Get three bids for the renovation scope.',
        ownerId: 'p-jordan',
        reviewerId: 'p-me',
        dueDate: '2026-08-02',
        priority: 'High',
        status: 'In progress',
        checklist: [
          { id: 'c5', text: 'Shortlist 5 contractors', done: true },
          { id: 'c6', text: 'Send scope to 3', done: true },
          { id: 'c7', text: 'Collect bids', done: false },
        ],
        dependencies: ['t1'],
        comments: [],
        revisions: [],
      },
      {
        id: 't3',
        title: 'Permit application',
        description: 'Submit renovation permits to the city.',
        ownerId: 'p-jordan',
        reviewerId: 'p-me',
        dueDate: '2026-07-18',
        priority: 'Medium',
        status: 'Blocked',
        checklist: [
          { id: 'c8', text: 'Fill forms', done: true },
          { id: 'c9', text: 'Submit', done: false },
        ],
        dependencies: [],
        comments: [{ id: 'cm2', authorId: 'p-jordan', text: 'Waiting on city to confirm the plan review slot.', at: '2026-07-19' }],
        revisions: [],
      },
    ],
    milestones: [
      { id: 'm1', title: 'Scope locked', dueDate: '2026-07-25', done: false, description: 'Renovation scope approved by all partners.' },
      { id: 'm2', title: 'Contractor selected', dueDate: '2026-08-10', done: false },
      { id: 'm3', title: 'Renovation complete', dueDate: '2026-12-15', done: false },
      { id: 'm4', title: 'Listed for sale', dueDate: '2026-01-15', done: false },
    ],
    files: [
      { id: 'f1', name: 'scope_v1.pdf', size: '240 KB', at: '2026-07-21' },
      { id: 'f2', name: 'property_photos.zip', size: '12 MB', at: '2026-07-10' },
    ],
    notes: 'Target sale price: $560K. Renovation budget: $95K. Hold budget: 5 months.',
    decisions: [
      { id: 'd1', title: 'Use LVP flooring throughout', decidedAt: '2026-07-15', by: 'p-jordan', rationale: 'Better durability and cost vs hardwood.' },
    ],
    activity: [
      { id: 'a1', at: '2026-07-22', text: 'Scope submitted for review', actorId: 'p-me' },
      { id: 'a2', at: '2026-07-20', text: 'Permit application blocked', actorId: 'p-jordan' },
      { id: 'a3', at: '2026-07-15', text: 'Space created from opportunity', actorId: 'p-jordan' },
    ],
    modules: baseModules([{ kind: 'property_tracker', label: 'Property Tracker' }, { kind: 'budget', label: 'Budget' }, { kind: 'vendors', label: 'Vendors' }]),
    record: {
      projectName: 'East Austin Bungalow Flip',
      opportunityCreatorId: 'p-jordan',
      ideaOrigin: 'Jordan identified the property and brought it under contract.',
      beganAt: '2026-07-15',
      participants: [
        { profileId: 'p-jordan', role: 'Lead Investor', expectedContribution: 'Capital and acquisition', responsibilities: 'Funding, contractor selection, sale' },
        { profileId: 'p-me', role: 'Project Manager', expectedContribution: 'Project management and scope', responsibilities: 'Scope, schedule, permits, QA' },
      ],
      goals: ['Complete renovation in 5 months', 'List and sell within 7 months', 'Target 18%+ return'],
      milestones: ['Scope locked', 'Contractor selected', 'Renovation complete', 'Listed for sale'],
      communicationExpectations: 'Weekly check-in, async updates in team chat, decisions logged in Decision Log.',
      majorDecisions: [{ id: 'd1', title: 'Use LVP flooring throughout', decidedAt: '2026-07-15', by: 'p-jordan', rationale: 'Better durability and cost vs hardwood.' }],
      acknowledgments: ['p-jordan'],
    },
    checkIns: [
      { id: 'ci1', at: '2026-07-21', frequency: 'Weekly', responses: [{ question: 'Is the project still active?', answer: 'Yes' }, { question: 'Are roles still accurate?', answer: 'Yes' }], notes: 'On track.' },
    ],
    checkInFrequency: 'Weekly',
    nextCheckIn: '2026-07-28',
  },
  {
    id: 'cs-tech',
    opportunityId: 'o-tech',
    name: 'Fintech Onboarding Product',
    description: 'Building a guided onboarding flow for a consumer fintech app.',
    mission: 'Create a frictionless, compliant onboarding experience that gets users to their first successful action faster than any competitor.',
    successDefinition: 'Onboarding flow shipped to production with <10% drop-off rate, KYC compliance verified, and positive user feedback from beta cohort.',
    memberIds: ['p-maya', 'p-sam', 'p-me'],
    roles: { 'p-maya': 'Design Lead', 'p-sam': 'Lead Engineer', 'p-me': 'Product Lead' },
    tasks: [
      {
        id: 't4',
        title: 'Onboarding flow wireframes',
        description: 'Low-fidelity wireframes for the 5-step onboarding flow.',
        ownerId: 'p-maya',
        reviewerId: 'p-me',
        dueDate: '2026-07-20',
        priority: 'High',
        status: 'Changes requested',
        checklist: [
          { id: 'c10', text: 'Step 1 welcome', done: true },
          { id: 'c11', text: 'Step 2 identity', done: true },
          { id: 'c12', text: 'Step 3 link bank', done: true, submittedForReview: true },
          { id: 'c13', text: 'Step 4 goals', done: false },
          { id: 'c14', text: 'Step 5 confirm', done: false },
        ],
        dependencies: [],
        comments: [],
        revisions: [
          { version: 1, at: '2026-07-18', by: 'p-maya', note: 'Initial submission', status: 'Ready for review' },
          { version: 1, at: '2026-07-19', by: 'p-me', note: 'Changes requested', status: 'Changes requested' },
        ],
        feedback: {
          id: 'fb1',
          reviewerId: 'p-me',
          whatNeedsToChange: 'Step 3 needs a clearer explanation of why we link a bank.',
          whyItNeedsToChange: 'Users drop off when trust is unclear at this step.',
          required: true,
          comments: 'Also consider a skip option for now.',
          at: '2026-07-19',
        },
      },
      {
        id: 't5',
        title: 'Build identity verification component',
        description: 'Frontend component for step 2 identity capture.',
        ownerId: 'p-sam',
        reviewerId: 'p-me',
        dueDate: '2026-07-30',
        priority: 'High',
        status: 'Not started',
        checklist: [
          { id: 'c15', text: 'Scaffold component', done: false },
          { id: 'c16', text: 'Integrate vendor SDK', done: false },
          { id: 'c17', text: 'Add error states', done: false },
        ],
        dependencies: ['t4'],
        comments: [],
        revisions: [],
      },
      {
        id: 't6',
        title: 'Design system tokens',
        description: 'Define color, type, and spacing tokens.',
        ownerId: 'p-maya',
        reviewerId: 'p-sam',
        dueDate: '2026-07-15',
        priority: 'Medium',
        status: 'Approved',
        checklist: [
          { id: 'c18', text: 'Color tokens', done: true },
          { id: 'c19', text: 'Type scale', done: true },
          { id: 'c20', text: 'Spacing scale', done: true },
        ],
        dependencies: [],
        comments: [{ id: 'cm3', authorId: 'p-sam', text: 'Approved. Clean and reusable.', at: '2026-07-14' }],
        revisions: [
          { version: 1, at: '2026-07-13', by: 'p-maya', note: 'Initial submission', status: 'Ready for review' },
          { version: 1, at: '2026-07-14', by: 'p-sam', note: 'Approved', status: 'Approved' },
        ],
      },
    ],
    milestones: [
      { id: 'm5', title: 'Wireframes approved', dueDate: '2026-07-22', done: false },
      { id: 'm6', title: 'Component library v1', dueDate: '2026-08-15', done: false },
      { id: 'm7', title: 'Onboarding v1 shipped', dueDate: '2026-09-15', done: false },
    ],
    files: [
      { id: 'f3', name: 'design_tokens.json', size: '8 KB', at: '2026-07-13' },
      { id: 'f4', name: 'wireframes_v1.fig', size: '4 MB', at: '2026-07-18' },
    ],
    notes: 'Target: 70% onboarding completion. North star: first successful transfer.',
    decisions: [
      { id: 'd2', title: 'Use Tailwind for design tokens', decidedAt: '2026-07-12', by: 'p-sam', rationale: 'Matches stack and speeds up implementation.' },
    ],
    activity: [
      { id: 'a4', at: '2026-07-19', text: 'Changes requested on wireframes', actorId: 'p-me' },
      { id: 'a5', at: '2026-07-14', text: 'Design tokens approved', actorId: 'p-sam' },
      { id: 'a6', at: '2026-07-10', text: 'Space created', actorId: 'p-sam' },
    ],
    modules: baseModules([{ kind: 'hiring', label: 'Hiring' }, { kind: 'investors', label: 'Investors' }]),
    record: {
      projectName: 'Fintech Onboarding Product',
      opportunityCreatorId: 'p-sam',
      ideaOrigin: 'Sam identified the onboarding gap from prior fintech work.',
      beganAt: '2026-07-10',
      participants: [
        { profileId: 'p-sam', role: 'Lead Engineer', expectedContribution: 'Backend and frontend build', responsibilities: 'Architecture, API, component build' },
        { profileId: 'p-maya', role: 'Design Lead', expectedContribution: 'Design and tokens', responsibilities: 'Wireframes, design system, QA design' },
        { profileId: 'p-me', role: 'Product Lead', expectedContribution: 'Product and review', responsibilities: 'Specs, reviews, roadmap' },
      ],
      goals: ['Ship onboarding v1 in 8 weeks', 'Reach 70% completion', 'Reusable design system'],
      milestones: ['Wireframes approved', 'Component library v1', 'Onboarding v1 shipped'],
      communicationExpectations: 'Async in team chat, weekly sync, all design changes reviewed by product.',
      majorDecisions: [{ id: 'd2', title: 'Use Tailwind for design tokens', decidedAt: '2026-07-12', by: 'p-sam', rationale: 'Matches stack.' }],
      acknowledgments: ['p-sam', 'p-maya'],
    },
    checkIns: [
      { id: 'ci2', at: '2026-07-17', frequency: 'Weekly', responses: [{ question: 'Is the project still active?', answer: 'Yes' }, { question: 'Are responsibilities being met?', answer: 'Mostly — wireframes delayed' }] },
    ],
    checkInFrequency: 'Weekly',
    nextCheckIn: '2026-07-24',
  },
  {
    id: 'cs-doc',
    opportunityId: 'o-doc',
    name: 'Coastlines II — Climate Short',
    description: 'A 20-minute climate documentary short. Footage captured; story and edit in progress.',
    mission: 'Tell a compelling, visually stunning climate story that moves audiences to understand coastal erosion impacts and drives action.',
    successDefinition: 'Film completed and accepted to at least 2 festivals, positive audience feedback, and distribution secured.',
    memberIds: ['p-me', 'p-marcus'],
    roles: { 'p-me': 'Co-producer', 'p-marcus': 'Director/Editor' },
    tasks: [
      {
        id: 't7',
        title: 'Story outline and beat sheet',
        description: 'Structure the 20-minute cut into beats.',
        ownerId: 'p-marcus',
        reviewerId: 'p-me',
        dueDate: '2026-07-28',
        priority: 'High',
        status: 'In progress',
        checklist: [
          { id: 'c21', text: 'Theme', done: true },
          { id: 'c22', text: 'Characters', done: true },
          { id: 'c23', text: 'Beat list', done: false },
        ],
        dependencies: [],
        comments: [],
        revisions: [],
      },
      {
        id: 't8',
        title: 'Selects from footage log',
        description: 'Pull selects for the opening sequence.',
        ownerId: 'p-marcus',
        reviewerId: 'p-me',
        dueDate: '2026-08-05',
        priority: 'Medium',
        status: 'Not started',
        checklist: [
          { id: 'c24', text: 'Log tape 1', done: false },
          { id: 'c25', text: 'Log tape 2', done: false },
        ],
        dependencies: ['t7'],
        comments: [],
        revisions: [],
      },
    ],
    milestones: [
      { id: 'm8', title: 'Story locked', dueDate: '2026-08-01', done: false },
      { id: 'm9', title: 'Rough cut', dueDate: '2026-09-15', done: false },
      { id: 'm10', title: 'Picture lock', dueDate: '2026-10-15', done: false },
    ],
    files: [{ id: 'f5', name: 'footage_log.csv', size: '120 KB', at: '2026-07-10' }],
    notes: 'Festival deadline: Nov 1. Runtime target: 20 min.',
    decisions: [],
    activity: [
      { id: 'a7', at: '2026-07-12', text: 'Space created', actorId: 'p-marcus' },
    ],
    modules: baseModules([{ kind: 'contacts', label: 'Contacts' }, { kind: 'budget', label: 'Budget' }]),
    record: {
      projectName: 'Coastlines II — Climate Short',
      opportunityCreatorId: 'p-marcus',
      ideaOrigin: 'Marcus shot the footage and originated the story.',
      beganAt: '2026-07-12',
      participants: [
        { profileId: 'p-marcus', role: 'Director/Editor', expectedContribution: 'Story and edit', responsibilities: 'Outline, selects, cut' },
        { profileId: 'p-me', role: 'Co-producer', expectedContribution: 'Production support and review', responsibilities: 'Schedule, budget, reviews' },
      ],
      goals: ['Picture lock in 12 weeks', 'Submit to 3 festivals', 'Deliver 20-minute cut'],
      milestones: ['Story locked', 'Rough cut', 'Picture lock'],
      communicationExpectations: 'Weekly sync, async notes in chat.',
      majorDecisions: [],
      acknowledgments: ['p-marcus'],
    },
    checkIns: [],
    checkInFrequency: 'Weekly',
    nextCheckIn: '2026-07-26',
  },
  {
    id: 'cs-clean',
    opportunityId: 'o-clean',
    name: 'Bright & Co Cleaning — Ops Build',
    description: 'Operations partnership to scale Bright & Co Cleaning to 30 recurring clients.',
    mission: 'Build a repeatable operations system that lets Bright & Co deliver consistent, high-quality cleaning at scale without sacrificing quality.',
    successDefinition: '30 recurring clients secured, QA checklist adopted by all staff, hiring pipeline live, and 90% client retention rate.',
    memberIds: ['p-priya', 'p-me'],
    roles: { 'p-priya': 'Operations Lead', 'p-me': 'Ops Advisor' },
    tasks: [
      {
        id: 't9',
        title: 'Standardize QA checklist',
        description: 'Create a per-visit QA checklist for staff.',
        ownerId: 'p-priya',
        reviewerId: 'p-me',
        dueDate: '2026-07-24',
        priority: 'High',
        status: 'Ready for review',
        checklist: [
          { id: 'c26', text: 'Draft checklist', done: true },
          { id: 'c27', text: 'Pilot with 2 staff', done: true },
          { id: 'c28', text: 'Revise from pilot', done: true, submittedForReview: true },
        ],
        dependencies: [],
        comments: [],
        revisions: [{ version: 1, at: '2026-07-22', by: 'p-priya', note: 'Pilot complete', status: 'Ready for review' }],
      },
      {
        id: 't10',
        title: 'Hiring pipeline v1',
        description: 'Define the hiring process for new cleaning staff.',
        ownerId: 'p-me',
        reviewerId: 'p-priya',
        dueDate: '2026-08-01',
        priority: 'Medium',
        status: 'Not started',
        checklist: [
          { id: 'c29', text: 'Job posting draft', done: false },
          { id: 'c30', text: 'Interview rubric', done: false },
        ],
        dependencies: [],
        comments: [],
        revisions: [],
      },
    ],
    milestones: [
      { id: 'm11', title: 'QA checklist live', dueDate: '2026-07-28', done: false },
      { id: 'm12', title: 'Hiring pipeline live', dueDate: '2026-08-10', done: false },
      { id: 'm13', title: '30 recurring clients', dueDate: '2026-06-01', done: false },
    ],
    files: [{ id: 'f6', name: 'qa_checklist_v1.pdf', size: '90 KB', at: '2026-07-22' }],
    notes: 'Current: 12 clients, 3 staff. Target: 30 clients, 6 staff.',
    decisions: [],
    activity: [
      { id: 'a8', at: '2026-07-22', text: 'QA checklist submitted for review', actorId: 'p-priya' },
      { id: 'a9', at: '2026-07-08', text: 'Space created', actorId: 'p-priya' },
    ],
    modules: baseModules([{ kind: 'customer_pipeline', label: 'Customer Pipeline' }, { kind: 'hiring', label: 'Hiring' }, { kind: 'equipment_tracker', label: 'Equipment Tracker' }]),
    record: {
      projectName: 'Bright & Co Cleaning — Ops Build',
      opportunityCreatorId: 'p-priya',
      ideaOrigin: 'Priya founded Bright & Co and is seeking an ops partner.',
      beganAt: '2026-07-08',
      participants: [
        { profileId: 'p-priya', role: 'Operations Lead', expectedContribution: 'Day-to-day ops', responsibilities: 'Scheduling, hiring, QA' },
        { profileId: 'p-me', role: 'Ops Advisor', expectedContribution: 'Advisory and review', responsibilities: 'Process design, reviews' },
      ],
      goals: ['Reach 30 recurring clients', 'Build hiring pipeline', 'Standardize QA'],
      milestones: ['QA checklist live', 'Hiring pipeline live', '30 recurring clients'],
      communicationExpectations: 'Weekly check-in, async in chat.',
      majorDecisions: [],
      acknowledgments: ['p-priya'],
    },
    checkIns: [],
    checkInFrequency: 'Weekly',
    nextCheckIn: '2026-07-30',
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-maya',
    type: 'direct',
    title: 'Maya Chen',
    participantIds: ['p-me', 'p-maya'],
    messages: [
      { id: 'msg1', authorId: 'p-maya', text: 'Hey! Saw you are on the fintech onboarding opportunity. Want to sync on the wireframes?', at: '2026-07-19T10:00:00' },
      { id: 'msg2', authorId: 'p-me', text: 'Yes — I left changes requested. Want to hop on a call Thursday?', at: '2026-07-19T10:30:00' },
      { id: 'msg3', authorId: 'p-maya', text: 'Thursday works. I will revise step 3 first.', at: '2026-07-19T10:35:00' },
    ],
  },
  {
    id: 'conv-flip',
    type: 'space',
    title: 'East Austin Bungalow Flip — Team',
    participantIds: ['p-me', 'p-jordan'],
    spaceId: 'cs-flip',
    messages: [
      { id: 'msg4', authorId: 'p-jordan', text: 'Scope looks good. One question on flooring budget.', at: '2026-07-22T09:00:00' },
      { id: 'msg5', authorId: 'p-me', text: 'LVP is $4k under the hardwood line. I will send the comparison.', at: '2026-07-22T09:10:00' },
    ],
  },
  {
    id: 'conv-tech',
    type: 'space',
    title: 'Fintech Onboarding Product — Team',
    participantIds: ['p-me', 'p-maya', 'p-sam'],
    spaceId: 'cs-tech',
    messages: [
      { id: 'msg6', authorId: 'p-sam', text: 'Design tokens are merged. Starting on identity component.', at: '2026-07-20T11:00:00' },
      { id: 'msg7', authorId: 'p-maya', text: 'Great. I will have step 3 revisions by Friday.', at: '2026-07-20T11:05:00' },
    ],
  },
  {
    id: 'conv-jordan',
    type: 'direct',
    title: 'Jordan Reyes',
    participantIds: ['p-me', 'p-jordan'],
    messages: [
      { id: 'msg8', authorId: 'p-jordan', text: 'Permit is blocked on the city slot. Might push us a week.', at: '2026-07-19T14:00:00' },
    ],
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', kind: 'review_requested', text: 'Priya submitted the QA checklist for your review.', at: '2026-07-22T08:00:00', read: false, link: 'space:cs-clean' },
  { id: 'n2', kind: 'review_requested', text: 'You submitted the renovation scope to Jordan.', at: '2026-07-21T17:00:00', read: false, link: 'space:cs-flip' },
  { id: 'n3', kind: 'review_completed', text: 'Changes requested on Onboarding flow wireframes.', at: '2026-07-19T16:00:00', read: true, link: 'space:cs-tech' },
  { id: 'n4', kind: 'task_due', text: 'Permit application is overdue.', at: '2026-07-18T08:00:00', read: true, link: 'space:cs-flip' },
  { id: 'n5', kind: 'check_in', text: 'Weekly check-in due for East Austin Bungalow Flip.', at: '2026-07-21T09:00:00', read: false, link: 'space:cs-flip' },
  { id: 'n6', kind: 'message', text: 'Maya Chen sent you a message.', at: '2026-07-19T10:00:00', read: true, link: 'messages' },
];

export const MY_TRUST: TrustState = {
  accountStanding: 'Good standing',
  reports: [],
  appealStatus: undefined,
  safetyGuidanceRead: true,
  fraudAlerts: [
    { id: 'fa1', type: 'Unusual login location', severity: 'low', status: 'resolved', detectedAt: '2026-06-28', description: 'Login from a new device in a different region. Verified by user via email confirmation.' },
    { id: 'fa2', type: 'Rapid account creation pattern', severity: 'low', status: 'dismissed', detectedAt: '2026-05-15', description: 'Several accounts created from the same IP in a short window. Reviewed — shared coworking space, no coordinated activity found.' },
  ],
  collaborationReviews: [
    { id: 'cr1', spaceId: 'cs-tech', ventureTitle: 'Fintech Onboarding Product', reviewerId: 'p-maya', revieweeId: 'p-me', periodStart: '2026-07-10', periodEnd: '2026-07-20', text: 'Clear product direction and fast, useful reviews. Kept the team aligned.', at: '2026-07-20' },
    { id: 'cr2', spaceId: 'cs-flip', ventureTitle: 'East Austin Bungalow Flip', reviewerId: 'p-jordan', revieweeId: 'p-me', periodStart: '2026-07-15', periodEnd: '2026-07-22', text: 'Organized scope process and stayed on schedule. Good communicator.', at: '2026-07-22' },
  ],
  trustLayers: [
    { number: 1, name: 'Email Verification', shortDescription: 'Confirms you control a valid email address. Does not verify identity or professional experience.', detail: 'Confirms control of a valid email address — not identity or experience.', userStatus: 'verified', userDetail: 'demo@opportunitynetwork.app verified on 2026-03-12' },
    { number: 2, name: 'Phone Verification', shortDescription: 'Confirms ownership of a valid phone number as an additional account security measure.', detail: 'Additional account security measure.', userStatus: 'verified', userDetail: 'Phone number verified on 2026-03-12' },
    { number: 3, name: 'Identity Verification', shortDescription: 'Identity verified through an approved third-party provider (e.g. Persona, Veriff, Stripe Identity). Confirms identity — not character, ability, or trustworthiness.', detail: 'Third-party identity verification. Confirms identity — not character, ability, or trustworthiness.', userStatus: 'verified', userDetail: 'Identity verified via Persona on 2026-03-12' },
    { number: 4, name: 'Verified Collaboration', shortDescription: 'Collaboration history earned through platform evidence — same Collaboration Space, verified membership, shared project history, recorded activity, completed work. Users cannot manually create verified collaboration history.', detail: 'Earned through platform evidence — not self-declared.', userStatus: 'verified', userDetail: '4 verified collaborations across 2 spaces' },
    { number: 5, name: 'Collaboration Reviews', shortDescription: 'Reviews only from verified participants of the same Collaboration Space. Each review is linked to the venture, period, reviewer, and date. The platform verifies who wrote it and that the collaboration occurred — not the subjective opinions expressed.', detail: 'Only verified co-participants can review. Platform verifies authorship and collaboration — not opinions.', userStatus: 'verified', userDetail: '2 reviews received, 1 given' },
    { number: 6, name: 'Trust & Fraud Detection', shortDescription: 'Continuous monitoring for suspicious behavior: coordinated reviews, fake collaboration patterns, reference inflation, identity fraud, and unusual account activity. May trigger manual review, restrictions, suspension, or removal.', detail: 'Continuous monitoring for suspicious behavior patterns.', userStatus: 'verified', userDetail: 'No active concerns on your account' },
  ],
  verificationTimeline: [
    { id: 'vt1', label: 'Email verified', type: 'email', status: 'verified', at: '2026-03-12', detail: 'demo@opportunitynetwork.app' },
    { id: 'vt2', label: 'Phone verified', type: 'phone', status: 'verified', at: '2026-03-12', detail: 'Phone number confirmed via SMS' },
    { id: 'vt3', label: 'Identity verified', type: 'identity', status: 'verified', at: '2026-03-12', detail: 'Persona identity check completed' },
    { id: 'vt4', label: 'Employment verified', type: 'employment', status: 'verified', at: '2026-04-02', detail: 'Senior Product Manager at Stripe (confirmed)' },
    { id: 'vt5', label: 'Venture participation verified', type: 'venture_participation', status: 'verified', at: '2026-04-18', detail: 'Fintech Onboarding Product — verified collaboration' },
    { id: 'vt6', label: 'References verified', type: 'reference', status: 'verified', at: '2026-05-10', detail: '2 references confirmed by verified collaborators' },
    { id: 'vt7', label: 'Business ownership verified', type: 'business_ownership', status: 'pending', at: '2026-07-15', detail: 'LLC registration pending third-party confirmation' },
  ],
};

export function getProfile(id: ID): Profile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function getOpportunity(id: ID): Opportunity | undefined {
  return OPPORTUNITIES.find((o) => o.id === id);
}

export function getSpace(id: ID): CollaborationSpace | undefined {
  return SPACES.find((s) => s.id === id);
}
