/*
# Phase 4.1 — Trust Foundation

## Purpose
Establishes the foundational trust schema that all subsequent Trust Engine phases
(4.2 through 4.9) depend on. This migration creates three new tables:
trust_audit_records, trust_event_log, and trust_config.

No existing tables are modified. No existing data is touched. This migration is
independently rollback-able — the new tables can be dropped without affecting
any existing functionality.

## Constitutional Compliance
- Article I (Trust is Earned, Not Bought): No payment or subscription data is
  referenced. The trust_config table has no payment-related columns.
- Article II (Verified Facts, Not Scores): trust_config stores thresholds and
  criteria, not score formulas. No aggregate score columns exist.
- Article V (Transparency and Appeal): trust_audit_records provides the immutable
  audit trail required for every trust-affecting decision.
- Article VI (Layer Separation): All tables are Trust Layer tables. RLS policies
  enforce that only admins can write to trust_audit_records and trust_config.
  trust_event_log is system-generated (insert via RPC only in future phases).

## New Tables

### trust_audit_records
Immutable record of every trust-affecting decision (verification, badge award,
fraud alert, appeal outcome, review publication). Separate from admin_audit_log
because trust decisions have different concerns, different retention needs, and
must be independently auditable per Constitution Article V.
- id (uuid, primary key)
- actor_id (uuid, references auth.users) — who or what made the decision
- actor_type (text) — 'admin', 'system', or 'user'
- decision_type (text) — e.g. 'verification.approve', 'badge.award', 'fraud.resolve'
- target_type (text) — affected record type (e.g. 'verification_claim', 'trust_badge')
- target_id (text) — affected record id
- reason (text) — explanation for the decision
- previous_state (jsonb) — state snapshot before the decision
- new_state (jsonb) — state snapshot after the decision
- created_at (timestamptz) — when the decision was recorded

### trust_event_log
Chronological log of trust-affecting events generated by the system (not by users).
System-generated events like: collaboration verified, review published, badge earned,
fraud pattern detected. This is the system's own record of what happened in the
trust layer, separate from user-facing audit records.
- id (uuid, primary key)
- event_type (text) — e.g. 'collaboration.verified', 'badge.earned', 'review.published'
- target_type (text) — affected record type
- target_id (text) — affected record id
- user_id (uuid, references auth.users, nullable) — the user the event pertains to
- metadata (jsonb) — additional event-specific data
- created_at (timestamptz) — when the event occurred

### trust_config
Admin-managed configuration for trust thresholds, badge criteria, and reputation
weights. Not hardcoded — admins can adjust trust parameters without code changes.
- id (uuid, primary key)
- key (text, unique) — configuration key (e.g. 'min_collaboration_tasks', 'review_window_days')
- value (jsonb) — configuration value (supports any JSON structure)
- description (text) — human-readable explanation of what this config controls
- updated_by (uuid, references auth.users) — admin who last updated this config
- updated_at (timestamptz) — when this config was last updated
- created_at (timestamptz) — when this config was first created

## Security
- RLS enabled on all three tables.
- trust_audit_records: admin-only SELECT and INSERT. No UPDATE or DELETE (immutable).
- trust_event_log: all authenticated users can SELECT (trust events are transparent
  per Constitution Article V). INSERT is admin-only for now (future phases will
  use SECURITY DEFINER RPCs for system-generated events). No UPDATE or DELETE.
- trust_config: admin-only SELECT, INSERT, UPDATE. No DELETE (config history retained).

## Important Notes
1. Trust audit is separate from admin audit (admin_audit_log). Different concerns,
   different retention, different access patterns.
2. Trust config is admin-managed, not hardcoded. Future phases will read from this
   table instead of using hardcoded thresholds.
3. No existing tables are altered. No existing data is touched.
4. trust_event_log SELECT is open to authenticated users because the Trust Constitution
   (Article V) requires transparency of trust-affecting decisions. However, the
   metadata jsonb column may contain sensitive details — future phases may add a
   column-level policy or a filtered view if needed.
5. The is_admin() function from Phase 3.1 is reused for admin-only policies.
*/

-- ============================================================
-- Table: trust_audit_records
-- ============================================================
CREATE TABLE IF NOT EXISTS trust_audit_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_type text NOT NULL DEFAULT 'admin',
  decision_type text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  reason text DEFAULT '',
  previous_state jsonb,
  new_state jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE trust_audit_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trust_audit_select" ON trust_audit_records;
CREATE POLICY "trust_audit_select" ON trust_audit_records
  FOR SELECT TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "trust_audit_insert" ON trust_audit_records;
CREATE POLICY "trust_audit_insert" ON trust_audit_records
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

-- No UPDATE or DELETE policies: immutable at the RLS level.

CREATE INDEX IF NOT EXISTS idx_trust_audit_records_created_at ON trust_audit_records (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trust_audit_records_target ON trust_audit_records (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_trust_audit_records_decision_type ON trust_audit_records (decision_type);
CREATE INDEX IF NOT EXISTS idx_trust_audit_records_actor_id ON trust_audit_records (actor_id);

-- ============================================================
-- Table: trust_event_log
-- ============================================================
CREATE TABLE IF NOT EXISTS trust_event_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE trust_event_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trust_event_log_select" ON trust_event_log;
CREATE POLICY "trust_event_log_select" ON trust_event_log
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "trust_event_log_insert" ON trust_event_log;
CREATE POLICY "trust_event_log_insert" ON trust_event_log
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

-- No UPDATE or DELETE policies: immutable event log.

CREATE INDEX IF NOT EXISTS idx_trust_event_log_created_at ON trust_event_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trust_event_log_event_type ON trust_event_log (event_type);
CREATE INDEX IF NOT EXISTS idx_trust_event_log_user_id ON trust_event_log (user_id);
CREATE INDEX IF NOT EXISTS idx_trust_event_log_target ON trust_event_log (target_type, target_id);

-- ============================================================
-- Table: trust_config
-- ============================================================
CREATE TABLE IF NOT EXISTS trust_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value jsonb NOT NULL,
  description text DEFAULT '',
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE trust_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trust_config_select" ON trust_config;
CREATE POLICY "trust_config_select" ON trust_config
  FOR SELECT TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "trust_config_insert" ON trust_config;
CREATE POLICY "trust_config_insert" ON trust_config
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "trust_config_update" ON trust_config;
CREATE POLICY "trust_config_update" ON trust_config
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- No DELETE policy: config history is retained.

CREATE INDEX IF NOT EXISTS idx_trust_config_key ON trust_config (key);

-- ============================================================
-- Seed default trust configuration
-- ============================================================
INSERT INTO trust_config (key, value, description) VALUES
  ('min_collaboration_tasks', '3', 'Minimum completed tasks for a collaboration to be considered verified (Phase 4.2)'),
  ('min_collaboration_decisions', '1', 'Minimum decisions participated in for collaboration verification (Phase 4.2)'),
  ('review_eligibility_window_days', '90', 'Days after collaboration ends during which a review can be submitted (Phase 4.3)'),
  ('review_draft_expiry_days', '30', 'Days a review can remain in draft before it expires (Phase 4.4)'),
  ('double_blind_reveal_requires_both', 'true', 'Whether both reviewer and reviewee must publish before identities are revealed (Phase 4.5)'),
  ('reputation_recalc_on_publish', 'true', 'Whether reputation summaries recalculate when a review is published (Phase 4.6)'),
  ('badge_auto_award_enabled', 'true', 'Whether badges are automatically awarded when criteria are met (Phase 4.7)'),
  ('recommendation_dismissal_retention_days', '365', 'How long dismissed recommendations are remembered (Phase 4.8)'),
  ('fraud_detection_enabled', 'true', 'Whether automated fraud pattern detection is active (Phase 4.9)')
ON CONFLICT (key) DO NOTHING;